### ISSUE TITLE
Refactor: TODO list

### ISSUE THREAD

**Issue by AlCalzone** [AlCalzone/node-zwave-js#4480]
- [x] Move all XyzCommand enums from `*CC.ts` files into `commandclass/_Types.ts`
- [x] Move all CC specific enums and types into `commandclass/_Types.ts`
- [x] Structure Controller commands by Serial API category (like misc/nvm/...)

Together with #4469 these should fix #4323
