### ISSUE TITLE
[Tracking] Deprecations and breaking changes for v10

### ISSUE THREAD

**Issue by AlCalzone** [AlCalzone/node-zwave-js#4564]
This issue is meant to collect deprecations and planned breaking changes for v10.

- [x] Make the `unprovision` argument to `Controller.beginExclusion` more logical (options object?)
- [x] `packages/zwave-js/src/lib/commandclass/_Types.ts`: `enum EventType`
- [x] `packages/zwave-js/src/lib/commandclass/_Types.ts`: `enum RecordStatus`
- [x] `packages/zwave-js/src/lib/commandclass/_Types.ts`: `type Association`
- [x] `packages/zwave-js/src/lib/commandclass/ConfigurationCC.ts`: `set` overload with 4 parameters
- [x] `packages/zwave-js/src/lib/controller/Controller.ts`: `beginInclusion` overload with `boolean` parameter
- [x] `packages/zwave-js/src/lib/controller/Controller.ts`: `getAssociationGroups`: overload with `number` parameter
- [x] `packages/zwave-js/src/lib/controller/Controller.ts`: `getAssociations`: overload with `number` parameter
- [x] `packages/zwave-js/src/lib/controller/Controller.ts`: `isAssociationAllowed` overload with `nodeId: number` parameter
- [x] `packages/zwave-js/src/lib/controller/Controller.ts`: `addAssociations` overload with `nodeId: number` parameter
- [x] `packages/zwave-js/src/lib/controller/Controller.ts`: `removeAssociations` overload with `nodeId: number` parameter
- [x] `packages/zwave-js/src/lib/controller/Controller.ts`: `replaceFailedNode` overload with `boolean` parameter
- [x] `packages/zwave-js/src/lib/driver/ZWaveOptions.ts`: `networkKey` option
