### ISSUE TITLE
[Tracking] Changes from 2024A specification package

### ISSUE THREAD

**Issue by AlCalzone** [AlCalzone/node-zwave-js#6752]
- [ ] Schedule Entry Lock CC v4, not deprecated
- [x] Humidity Control Mode CC max. is v1 not v2
- [x] Meter Table Push Configuration OBSOLETED
- [x] Proprietary CC OBSOLETED
- [ ] User Credentials CC, NEW
- [ ] Firmware Update Metadata v8

**Comment by AlCalzone** [comment]
Converted to individual issues
