### ISSUE TITLE
[Tracking] Changes from 2023B specification package

### ISSUE THREAD

**Issue by AlCalzone** [AlCalzone/node-zwave-js#6753]
- [ ] Schedule Entry Lock CC v4, not deprecated
- [ ] Humidity Control Mode CC max. is v1 not v2
- [ ] Meter Table Push Configuration OBSOLETED
- [ ] Proprietary CC OBSOLETED
- [ ] User Credentials CC, NEW
- [ ] Firmware Update Metadata v8
